// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkhYw4d4ZovKlhXQLnUFImzdvaTdCcyXM',
    appId: '1:842214022631:web:f6cba8cc6dea8619163142',
    messagingSenderId: '842214022631',
    projectId: 'guru-booking',
    authDomain: 'guru-booking.firebaseapp.com',
    storageBucket: 'guru-booking.appspot.com',
    measurementId: 'G-79PCQB9T04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNfrr9SvTr9ttHfMGmQDVTVTbmqzcbRk',
    appId: '1:842214022631:android:50b900ba62ce706f163142',
    messagingSenderId: '842214022631',
    projectId: 'guru-booking',
    databaseURL: 'https://guru-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guru-booking.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkhYw4d4ZovKlhXQLnUFImzdvaTdCcyXM',
    appId: '1:842214022631:web:12f71c03f4175861163142',
    messagingSenderId: '842214022631',
    projectId: 'guru-booking',
    authDomain: 'guru-booking.firebaseapp.com',
    databaseURL: 'https://guru-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guru-booking.appspot.com',
    measurementId: 'G-13QDS5LLVL',
  );

}